# Generated by Django 2.1.7 on 2019-04-23 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Visaletters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visa_No', models.PositiveIntegerField(default='000000')),
              
                ('Country', models.CharField(choices=[('INDIA', 'India'), ('USA', 'Usa'), ('UK', 'Uk'), ('CHINA', 'China'), ('JAPAN', 'Japan')], default='INDIA', max_length=264)),
                ('entry_from', models.DateField()),
                ('departure_to', models.DateField()),
                ('Number', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default='1', max_length=264)),
                ('purpose_of_visit', models.CharField(max_length=500)),
                ('Routes_and_Places', models.CharField(default='MOSCOW', max_length=500)),
                ('hotels', models.CharField(max_length=264, unique=True)),
                ('amount', models.PositiveIntegerField()),
                ('firstname_1', models.CharField(blank=True, max_length=264, unique=True)),
                ('lastname_1', models.CharField(blank=True, max_length=264, unique=True)),
                ('Passport_Number_1', models.CharField(blank=True, max_length=200, unique=True)),
                ('Date_Of_Birth_1', models.DateField(blank=True)),
                ('Sex_1', models.CharField(blank=True, max_length=100)),
                ('firstname_2', models.CharField(blank=True, max_length=264, unique=True)),
                ('lastname_2', models.CharField(blank=True, max_length=264, unique=True)),
                ('Passport_Number_2', models.CharField(blank=True, max_length=200, unique=True)),
                ('Date_Of_Birth_2', models.DateField(blank=True)),
                ('Sex_2', models.CharField(blank=True, max_length=100)),
                ('firstname_3', models.CharField(blank=True, max_length=264, unique=True)),
                ('Passport_Number_3', models.CharField(blank=True, max_length=200, unique=True)),
                ('Date_Of_Birth_3', models.DateField(blank=True)),
                ('Sex_3', models.CharField(blank=True, max_length=100)),
                ('firstname_4', models.CharField(blank=True, max_length=264, unique=True)),
                ('lastname_4', models.CharField(blank=True, max_length=264, unique=True)),
                ('Passport_Number_4', models.CharField(blank=True, max_length=200, unique=True)),
                ('Date_Of_Birth_4', models.DateField(blank=True)),
                ('Sex_4', models.CharField(blank=True, max_length=100)),
                ('Date_of_letter', models.DateField(blank=True)),
            ],
        ),
    ]
