# Generated by Django 2.1.7 on 2019-04-23 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generateletter', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visaletters',
            name='Passport_Number_3',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='visaletters',
            name='Passport_Number_4',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='visaletters',
            name='firstname_1',
            field=models.CharField(blank=True, max_length=264),
        ),
        migrations.AlterField(
            model_name='visaletters',
            name='firstname_2',
            field=models.CharField(blank=True, max_length=264),
        ),
        migrations.AlterField(
            model_name='visaletters',
            name='firstname_3',
            field=models.CharField(blank=True, max_length=264),
        ),
        migrations.AlterField(
            model_name='visaletters',
            name='firstname_4',
            field=models.CharField(blank=True, max_length=264),
        ),
        migrations.AlterField(
            model_name='visaletters',
            name='lastname_1',
            field=models.CharField(blank=True, max_length=264),
        ),
        migrations.AlterField(
            model_name='visaletters',
            name='lastname_2',
            field=models.CharField(blank=True, max_length=264),
        ),
        migrations.AlterField(
            model_name='visaletters',
            name='lastname_4',
            field=models.CharField(blank=True, max_length=264),
        ),
    ]
