# Generated by Django 2.1.7 on 2019-04-23 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generateletter', '0002_auto_20190423_1154'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visaletters',
            name='Date_Of_Birth_2',
        ),
        migrations.RemoveField(
            model_name='visaletters',
            name='Date_Of_Birth_4',
        ),
        migrations.RemoveField(
            model_name='visaletters',
            name='Date_of_letter',
        ),
        migrations.AlterField(
            model_name='visaletters',
            name='Date_Of_Birth_3',
            field=models.DateField(),
        ),
    ]
