# Generated by Django 2.1.7 on 2019-04-23 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generateletter', '0004_auto_20190423_1200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visaletters',
            name='Date_Of_Birth_1',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
