# Generated by Django 2.1.7 on 2019-04-23 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generateletter', '0006_auto_20190423_1206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visaletters',
            name='Date_Of_Birth_1',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='visaletters',
            name='Passport_Number_1',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='visaletters',
            name='Sex_1',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='visaletters',
            name='firstname_1',
            field=models.CharField(max_length=264),
        ),
        migrations.AlterField(
            model_name='visaletters',
            name='lastname_1',
            field=models.CharField(max_length=264),
        ),
    ]
