# Generated by Django 2.1.7 on 2019-04-23 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generateletter', '0007_auto_20190423_1249'),
    ]

    operations = [
        migrations.AddField(
            model_name='visaletters',
            name='Visa_Letter_Number',
            field=models.CharField(default='1', max_length=264),
        ),
    ]
