# Generated by Django 2.2 on 2019-04-24 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generateletter', '0008_visaletters_visa_letter_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visaletters',
            name='visa_No',
        ),
        migrations.AddField(
            model_name='visaletters',
            name='Organization',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='visaletters',
            name='Payment_status',
            field=models.CharField(choices=[('Paid', 'Paid'), ('unpaid', 'unpaid')], default='unpaid', max_length=200),
        ),
    ]
