# Generated by Django 2.2 on 2019-04-24 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generateletter', '0009_auto_20190424_0600'),
    ]

    operations = [
        migrations.AddField(
            model_name='visaletters',
            name='no_passenger',
            field=models.IntegerField(default=1),
        ),
    ]
