# Generated by Django 2.2 on 2019-04-25 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('generateletter', '0013_visaletters_multiplicity_of_visa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visaletters',
            name='Multiplicity_of_visa',
        ),
    ]
