# Generated by Django 2.1.7 on 2019-04-27 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generateletter', '0014_remove_visaletters_multiplicity_of_visa'),
    ]

    operations = [
        migrations.AddField(
            model_name='visaletters',
            name='Date_Of_Birth_5',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='visaletters',
            name='Passport_Number_5',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='visaletters',
            name='Sex_5',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='visaletters',
            name='firstname_5',
            field=models.CharField(blank=True, max_length=264),
        ),
        migrations.AddField(
            model_name='visaletters',
            name='lastname_5',
            field=models.CharField(blank=True, max_length=264),
        ),
    ]
