# Generated by Django 2.1.7 on 2019-04-27 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('generateletter', '0016_auto_20190427_0725'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visaletters',
            name='purpose_of_visit',
        ),
    ]
